### ISSUE TITLE
Starter

### ISSUE THREAD

**Issue by hauchongtang** [hauchongtang/studytgt#1]
# How to get started
## Clone and Add repo as remote 
1. `git clone https://github.com/hauchongtang/studytgt.git`
2. `git remote add origin https://github.com/hauchongtang/studytgt.git`
## After cloning
1. run `npm install` to install all node modules in the cloned repo
2. `npm start` to start the script.
## How to commit changes
1. `git add .` -> this will add all changes to staging area in git
3. `git commit -m <description of commit>` -> commit locally
4. `git push origin <branch-name>` or master (it is a branch too)

# Tools
### reactstrap
- Bootstrap integration
### 

# ToDo (Overview)
- [x] logo (decide on / make a logo)
- [x] styling of the navbar (css)
- [x] backend (hosted on another repo) [link-to-backend](https://github.com/hauchongtang/splatbackend)
- [x] review proposal then send in discord

# Workflow
1. Features / components will not be commited to master, INSTEAD -> `git checkout -b <name_of_feature>` (create a new branch or develop on existing feature branch)

**Comment by hauchongtang** [comment]
![image](https://user-images.githubusercontent.com/56034480/168406705-637f8664-3049-4b74-b6a4-f3c8af3cc366.png)
our landing page for now, details are in the commit pull request. Any comments?

**Comment by amzhy** [comment]
LGTM, perhaps the font size can be bigger (better readability for your users). Also better to consider live deployment early on(e.g vercel/heroku) to ensure that your frontend UI is rendered as expected.
