### ISSUE TITLE
Login / Sign up

### ISSUE THREAD

**Issue by hauchongtang** [hauchongtang/studytgt#8]
# ToDo

- [x] Handle failed login
- [x] Sign up page + styling (follow same as login)
- [x] Login page + styling
- [x] Sign up button on Login Page

# Login component is done #7 
- After login is SUCCESSFUL -> User is directed to homepage (get started)
- Demo here [Video Demo](https://github.com/hauchongtang/studytgt/tree/master/src/assets)
![image](https://user-images.githubusercontent.com/56034480/169103016-c9c4fa4b-1b1a-4f5e-aa54-a40a25dcadf6.png)

**Comment by hauchongtang** [comment]
refer to this pull request for more details #9 
![image](https://user-images.githubusercontent.com/56034480/169188593-574c26f2-e82f-4934-937e-fe4f3c74ebcb.png)
